common: &default_settings
  app_name: <%= Settings.new_relic.app_name %>
  license_key: <%= Settings.new_relic.key %>
  log_level: info

development:
  <<: *default_settings
  app_name: <%= Settings.new_relic.app_name %> (Development)
  developer_mode: true

test:
  <<: *default_settings
  monitor_mode: false

staging:
  <<: *default_settings
  app_name: <%= Settings.new_relic.app_name %> (Staging)

production:
  <<: *default_settings
